# Generated by Django 4.2.4 on 2023-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnamnesisLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("1", "Higher"),
                            ("2", "Specialized Secondary"),
                            ("3", "Secondary"),
                            ("4", "Incomplete Secondary"),
                            ("4", "Primary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "martial_status",
                    models.CharField(
                        choices=[
                            ("1", "Женат"),
                            ("2", "Замужем"),
                            ("3", "Разведен(а)"),
                            ("4", "Вдовец"),
                            ("5", "Вдова"),
                            ("6", "Холост"),
                            ("7", "Не замужем"),
                        ],
                        max_length=20,
                    ),
                ),
                ("place_work", models.CharField(max_length=125)),
                ("criminal_record", models.CharField(max_length=125)),
                ("previous_illnesses", models.CharField(max_length=125)),
                ("medications", models.CharField(max_length=125)),
                ("allergic_history", models.CharField(max_length=255)),
            ],
        ),
    ]
