# Generated by Django 4.2.4 on 2023-08-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="anamnesis_life",
        ),
        migrations.AddField(
            model_name="anamnesislife",
            name="patient",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anamnesis_life",
                to="patient.patient",
            ),
            preserve_default=False,
        ),
    ]
