# Generated by Django 4.2.4 on 2023-09-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_remove_patient_anamnesis_life_anamnesislife_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name="TypeIntoxication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="avatar",
            field=models.FileField(
                default="./static/django-logo-negative.png", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="anamnesislife",
            name="education",
            field=models.CharField(
                choices=[
                    ("1", "Высшее"),
                    ("2", "Средне-специальные"),
                    ("3", "Среднее"),
                    ("4", "Неполное среднее"),
                    ("5", "Начальное"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SomaticStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("1", "Удовлетворительное"),
                            ("2", "Средней тяжести"),
                            ("3", "Тяжелое"),
                            ("4", "Крайне тяжелое"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1", "Пониженного"),
                            ("2", "Повышенного питания"),
                            ("3", "Истощен"),
                            ("4", "Крайне тяжелое"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("1", "Обычные цвета"),
                            ("2", "Цианотические"),
                            ("3", "Акроцианоз"),
                            ("4", "Мраморные"),
                            ("5", "Бледные"),
                            ("6", "Гиперимированные"),
                            ("7", "Сухие"),
                            ("8", "Влажные"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("1", "Наличие шрамов"),
                            ("2", "Садин"),
                            ("3", "Ушибов"),
                            ("4", "Гематом"),
                            ("5", "Парезов"),
                            ("6", "Воспаления"),
                            ("7", "Сухие"),
                            ("8", "Влажные"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "traces",
                    models.CharField(
                        choices=[
                            ("1", "Наличие шрамов"),
                            ("2", "Ссадин"),
                            ("3", "Ушибов"),
                            ("4", "Гематом"),
                            ("5", "Парезов"),
                            ("6", "Воспаления"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "state_conjunctiva",
                    models.CharField(
                        choices=[
                            ("1", "Блеск глаз"),
                            ("2", "Гиперимия"),
                            ("3", "Икретичность"),
                        ],
                        max_length=25,
                    ),
                ),
                ("breath", models.CharField(max_length=25)),
                (
                    "wheezing",
                    models.CharField(
                        choices=[("1", "Хрипы нет"), ("2", "Хрипы есть")], max_length=25
                    ),
                ),
                ("bh", models.CharField(max_length=25)),
                ("saturation", models.CharField(max_length=25)),
                (
                    "heart_tones",
                    models.CharField(
                        choices=[
                            ("1", "Тоны ясные"),
                            ("2", "Приглушены"),
                            ("3", "Глухие"),
                            ("4", "Аритмичные"),
                        ],
                        max_length=25,
                    ),
                ),
                ("ad", models.CharField(max_length=25)),
                ("pulse_frequency", models.FloatField()),
                (
                    "filling",
                    models.CharField(
                        choices=[
                            ("1", "Тоны ясные"),
                            ("2", "Приглушены"),
                            ("3", "Глухие"),
                            ("4", "Аритмичные"),
                        ],
                        max_length=25,
                    ),
                ),
                ("tongue", models.CharField(blank=True, max_length=125, null=True)),
                ("stomach", models.CharField(blank=True, max_length=125, null=True)),
                ("liver", models.CharField(blank=True, max_length=125, null=True)),
                ("vomiting", models.CharField(blank=True, max_length=125, null=True)),
                ("stool", models.CharField(blank=True, max_length=125, null=True)),
                ("diuresis", models.CharField(blank=True, max_length=125, null=True)),
                ("edema", models.CharField(blank=True, max_length=125, null=True)),
                ("glucose", models.CharField(blank=True, max_length=125, null=True)),
                ("apparatus", models.CharField(blank=True, max_length=125, null=True)),
                ("vascular_system", models.CharField(max_length=125)),
                (
                    "supplements",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeurologicalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pupils",
                    models.CharField(
                        choices=[
                            ("1", "Нистагм"),
                            ("2", "Мидриаз"),
                            ("3", "Миоз"),
                            ("4", "Анизокория"),
                        ],
                        max_length=25,
                    ),
                ),
                ("photo_reaction", models.CharField(max_length=25)),
                (
                    "meningeal_signs",
                    models.CharField(
                        choices=[
                            ("1", "Ригидность затылочных мышц"),
                            ("2", "Симптом Кернинга"),
                            ("3", "Брудзинского"),
                        ],
                        max_length=25,
                    ),
                ),
                ("seizures", models.CharField(max_length=25)),
                ("dysarthria", models.CharField(max_length=25)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        choices=[("1", "Вид опрятен"), ("2", "Вид не опрятен")],
                        max_length=25,
                    ),
                ),
                ("smell_of_alcohol", models.BooleanField()),
                ("behavior", models.CharField(max_length=125)),
                ("consciousness", models.CharField(max_length=125)),
                ("orientation", models.CharField(max_length=125)),
                ("perception_disorders", models.CharField(max_length=125)),
                ("emotional_background", models.CharField(max_length=125)),
                ("night_sleep", models.CharField(max_length=125)),
                ("suicide_attempt", models.CharField(max_length=125)),
                ("causes_of_alcohol", models.CharField(max_length=125)),
                ("purpose_of_hospitalization", models.CharField(max_length=125)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnamnesisDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiving_something", models.CharField(max_length=255)),
                ("receiving_something_time", models.DateField(max_length=255)),
                ("somatic_disorders", models.CharField(max_length=255)),
                ("mental_disorders", models.CharField(max_length=255)),
                ("daily_tolerance", models.FloatField()),
                ("binge_drinking", models.CharField(max_length=25)),
                ("light_gaps", models.CharField(max_length=25)),
                ("duration_last_binge", models.CharField(max_length=25)),
                ("duration_last_remission", models.CharField(max_length=25)),
                ("last_treatment", models.CharField(max_length=25)),
                ("last_alcohol_intake", models.CharField(max_length=25)),
                ("dose", models.CharField(max_length=25)),
                ("addition", models.CharField(max_length=125)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ManyToManyField(to="patient.category")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "type_intoxication",
                    models.ManyToManyField(to="patient.typeintoxication"),
                ),
            ],
        ),
    ]
