# Generated by Django 4.2.4 on 2023-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_category_typeintoxication_patient_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePalimpsests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name="TypeTolerance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="in_hospital",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="avatar",
            field=models.FileField(default="./default_png.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="conditions",
            field=models.CharField(max_length=125),
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="type_palimpsests",
            field=models.ManyToManyField(to="patient.typepalimpsests"),
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="type_tolerance",
            field=models.ManyToManyField(to="patient.typetolerance"),
        ),
    ]
