# Generated by Django 4.2.4 on 2023-09-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_typepalimpsests_typetolerance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anamnesisdisease",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="mentalstatus",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="neurologicalstatus",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="somaticstatus",
            name="patient",
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="anamnesis",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.anamnesisdisease",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="mental",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.mentalstatus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="neurological",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.neurologicalstatus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="somatic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.somaticstatus",
            ),
            preserve_default=False,
        ),
    ]
