# Generated by Django 4.2.4 on 2023-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0007_remove_anamnesisdisease_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="in_hospital",
        ),
        migrations.AddField(
            model_name="patient",
            name="in_hospital",
            field=models.BooleanField(default=False),
        ),
    ]
