# Generated by Django 4.2.4 on 2023-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0008_remove_patientinfo_in_hospital_patient_in_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
