# Generated by Django 4.2.4 on 2023-10-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0012_alter_photo_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epicrisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_treatment", models.DateField()),
                ("end_treatment", models.DateField()),
                ("main_diagnosis", models.CharField(max_length=255)),
                ("concomitant", models.CharField(max_length=125)),
                ("complications", models.CharField(max_length=255)),
                ("laboratory_tests", models.CharField(max_length=255)),
                ("instrumental_studies", models.CharField(max_length=255)),
                ("ecg", models.CharField(max_length=255)),
                ("x_ray", models.CharField(max_length=125)),
                ("specialist_consultations", models.CharField(max_length=255)),
                ("treatment", models.CharField(max_length=255)),
                (
                    "treatment_results",
                    models.CharField(
                        choices=[
                            ("1", "Выздоровление"),
                            ("2", "Улучшение"),
                            ("3", "Без изменений"),
                            ("4", "Ухудшение"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "recommendations",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
