# Generated by Django 4.2.4 on 2023-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0016_alter_epicrisis_treatment_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
