# Generated by Django 4.2.4 on 2023-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0018_alter_patientinfo_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anamnesisdisease",
            name="category",
        ),
        migrations.RemoveField(
            model_name="anamnesisdisease",
            name="type_intoxication",
        ),
        migrations.RemoveField(
            model_name="anamnesisdisease",
            name="type_palimpsests",
        ),
        migrations.RemoveField(
            model_name="anamnesisdisease",
            name="type_tolerance",
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="category",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="type_intoxication",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="type_palimpsests",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anamnesisdisease",
            name="type_tolerance",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
