# Generated by Django 4.2.4 on 2024-01-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_remove_anamnesisdisease_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TypeIntoxication',
        ),
        migrations.DeleteModel(
            name='TypePalimpsests',
        ),
        migrations.DeleteModel(
            name='TypeTolerance',
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='conditions',
            field=models.CharField(choices=[('1', 'В состоянии алкольного опьянения'), ('2', 'Алкольного делирия'), ('3', 'Состоянии отмены алкоголя'), ('4', 'Состоянии отмены судорогами от алкоголя'), ('5', 'Others')], max_length=125),
        ),
    ]
