# Generated by Django 4.2.4 on 2024-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0020_delete_category_delete_typeintoxication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="avatar",
            field=models.FileField(default="./media/default_png.jpg", upload_to=""),
        ),
    ]
