# Generated by Django 4.2.4 on 2024-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0022_alter_patient_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="avatar",
            field=models.FileField(default="api/media/default_png.jpg", upload_to=""),
        ),
    ]
