# Generated by Django 4.2.4 on 2024-02-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0026_alter_neurologicalstatus_dysarthria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="somaticstatus",
            name="skin_type",
            field=models.CharField(max_length=128),
        ),
    ]
