# Generated by Django 4.2.4 on 2023-08-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("1", "Admin"),
                    ("2", "Doctor"),
                    ("3", "Psychologist"),
                    ("4", "Nurse"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255)),
                ("date_of_birth", models.CharField(max_length=255)),
                ("other_conditions", models.CharField(max_length=255)),
                ("escorts", models.CharField(max_length=125)),
                ("complaints", models.CharField(max_length=125)),
                ("date_of_admission", models.DateTimeField()),
                ("date_of_discharge", models.DateTimeField()),
                ("departament", models.IntegerField()),
                ("number_of_days", models.IntegerField()),
                ("blood_type", models.CharField(max_length=25)),
                (
                    "anamnesis_life",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.anamnesislife",
                    ),
                ),
            ],
        ),
    ]
