# Generated by Django 4.2.4 on 2023-08-25 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_name_alter_user_role_alter_user_surname_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
