# Generated by Django 4.2.4 on 2023-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_delete_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("1", "Admin"),
                    ("2", "Доктор"),
                    ("3", "Психолог"),
                    ("4", "Мед-Сестра"),
                ],
                max_length=20,
            ),
        ),
    ]
